### PR TITLE
Add Si4721 Receive and Transmit Support

### PR DESCRIPTION
**Pull request by NPoole**
Add:

- SI4721.h
- SI4721.ccp
- TestSI4721.ino
- TransmitSI4721.ino
- PairTestSI4721.ino

Change: 

- keywords.txt (added transmit function keywords)
- library.properties (version up to 1.3.0)

Differences in implementation for SI4721 compared to previously supported devices:

- Add the following functions to switch device modes and set transmit properties: setModeReceive(), setModeTransmit(), beginRDS(uint16_t programID = 0xBEEF), setRDSstation(char *s), setRDSbuffer(char *s), setTXpower(uint8_t pwr), ASQ_STATUS getASQ(), TX_STATUS getTuneStatus()
- Add setDeemphasis(uint8_t uS) and _fmDeemphasis for regional compatibility
- Add _transmitMode private bool to track device mode
- Add ASQ_STATUS and TX_STATUS structs for storing transmit status data
- Ambiguate 'Wire.function' to '_i2cPort->function' allowing users to specify their own i2c library and device address on init(). Default behavior is to use Wire library and default address is 0x63.

Example Code tested and working

### CODE REVIEW

**Comment by synth** [comment]
Have ya'll seen that [Sparkfun has an Si4721 breakout board](https://www.sparkfun.com/products/15853)? Also, they have [forked this repo](https://github.com/sparkfun/Qwiic_FM_Transceiver_Si4721) and added support for Si4721 :)

**Comment by NPoole** [comment]
@synth 

Yeah, that's my fork, haha. It was only supposed to be temporary until this PR was merged, but @mathertel hasn't had a chance to test it, which is understandable (p.s. @mathertel I'm sure we could send you a breakout board if you'd like) 

As to your question, that depends on what you mean by "simultaneously," If you really mean Tx and Rx in full-duplex then no. I'm not sure how desirable that would be even if it were possible, due to the nature of FM broadcast, but I'd be interested to hear your application. What it absolutely _will_ do is switch back and forth between Rx and Tx modes on the fly, so if you wanted to do something wacky like texting over RDS, you could just switch to Tx mode, broadcast your RDS and then switch back to Rx immediately. You wouldn't have to worry about missing anything while in Tx mode because all you'd be able to demodulate is yourself broadcasting anyway (there's no graceful way to handle collisions because you're really abusing the standard, lol) 

Hope that's helpful

**Comment by synth** [comment]
@NPoole Ha, awesome. Yea, I was curious about full duplex. It's good to know on the fly is possible though! Thanks!

**Comment by mathertel** [comment]
The reason I did not merge was because I did not find a board to check the quality.
I just don't want to leave a unusable library behind.
Did sparkfun added anything special or fixes ?

**Comment by mathertel** [comment]
@NPoole Great offer ! Find my address in https://www.mathertel.de/impressum.aspx :)

**Comment by NPoole** [comment]
Okay @mathertel, there should be a board on its way.

**Comment by mathertel** [comment]
Closed through Pull request https://github.com/mathertel/Radio/pull/45 that picked all changes.

**Pull request closed without merging**
